### ISSUE TITLE
人数和密度图的问题

### ISSUE THREAD

**Issue by eain3314** [ZhengPeng7/CSRNet_in_Keras#1]
密度图的ground-truth是根据标签生成的，然后根据密度图积分求和得到人数，对吗？
但是如果用一个随便找的图片进行测试的时候，没有标签，那怎么生成的密度图？
能解答一下吗

**Comment by ZhengPeng7** [comment]
直接用于输出结果的话肯定是没有标签密度图, 只有网络预测输出的密度图, 预测输出是根据原场景图生成的, 与标签密度图无关。
但如果你指的是输出结果并衡量是否准确的话, 那就需要你手工确认人头的位置, 然后将其坐标记录下来, 就像现有的数据集那样, 有了头部坐标自然能生成密度图了.
我不知道我说清楚没有.
