### ISSUE TITLE
换成我自己的数据集生成数据集

### ISSUE THREAD

**Issue by zhangsong1213** [ZhengPeng7/CSRNet_in_Keras#2]
我换成自己的数据集 再运行generate_datasets时候  报错
ValueError: operands could not be broadcast together with shapes (59,1819) (59,0) (59,1819) 
而且 是处理完一批数据之后才报错的

**Comment by ZhengPeng7** [comment]
推荐使用Dropbox链接下载数据集, 因为百度云的那个数据集中的坐标存在负值, 这是不合乎情理的.
因为存在负值, 所以在切片的时候, 某个维度上存在类似于[10:-4], 这之后导致0的出现.

**Comment by zhangsong1213** [comment]
明白了  多谢
 



------------------ 原始邮件 ------------------
发件人: "ZhengPeng"<notifications@github.com>; 
发送时间: 2019年7月3日(星期三) 上午10:44
收件人: "ZhengPeng7/CSRNet-Keras"<CSRNet-Keras@noreply.github.com>; 
抄送: "皺眉頭"<1148640196@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [ZhengPeng7/CSRNet-Keras] 换成我自己的数据集生成数据集 (#2)




推荐使用Dropbox链接下载数据集, 因为百度云的那个数据集中的坐标存在负值, 这是不合乎情理的.
 因为存在负值, 所以在切片的时候, 某个维度上存在类似于[10:-4], 这之后导致0的出现.

**Comment by zhangsong1213** [comment]
坐标产生负值原因 是什么  都是在一张图片上标记点  怎么可能 会产生负值呢
 



------------------ 原始邮件 ------------------
发件人: "ZhengPeng"<notifications@github.com>; 
发送时间: 2019年7月3日(星期三) 上午10:44
收件人: "ZhengPeng7/CSRNet-Keras"<CSRNet-Keras@noreply.github.com>; 
抄送: "皺眉頭"<1148640196@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [ZhengPeng7/CSRNet-Keras] 换成我自己的数据集生成数据集 (#2)




推荐使用Dropbox链接下载数据集, 因为百度云的那个数据集中的坐标存在负值, 这是不合乎情理的.
 因为存在负值, 所以在切片的时候, 某个维度上存在类似于[10:-4], 这之后导致0的出现.

**Comment by ZhengPeng7** [comment]
所以才说数据集本身存在问题, 记录坐标的文件读取出来就是有负值的, 两个不同来源的数据集互不一样, 我自己也是比较困惑的.

**Comment by zhangsong1213** [comment]
我自己 拿标记工具 制作了一批数据集 用代码对数据集进行预处理时  也发生了  同样的问题  标记工具是从 github上的一个 人群密度项目里面找的
 



------------------ 原始邮件 ------------------
发件人: "ZhengPeng"<notifications@github.com>; 
发送时间: 2019年7月3日(星期三) 上午10:56
收件人: "ZhengPeng7/CSRNet-Keras"<CSRNet-Keras@noreply.github.com>; 
抄送: "皺眉頭"<1148640196@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [ZhengPeng7/CSRNet-Keras] 换成我自己的数据集生成数据集 (#2)




所以才说数据集本身存在问题, 记录坐标的文件读取出来就是有负值的, 两个不同来源的数据集互不一样, 我自己也是比较困惑的.

**Comment by ZhengPeng7** [comment]
你可以把打印出来以便排查原因, 因为我说的产生0的原因是没有错的, 代码的处理也是没有问题的, 当然当然为了显出这类问题, 没有加对此类的异常点跳过处理.

**Comment by zhangsong1213** [comment]
额外多问你一个问题   用训练好的模型能不能生成人群对应的坐标   类似于mat文件一样  能的话  该怎样实现？祝老哥学业顺利  万事如意！

------------------ 原始邮件 ----------------
发件人: "ZhengPeng"<notifications@github.com>;
发送时间: 2019年7月4日(星期四) 上午9:17
收件人: "ZhengPeng7/CSRNet-Keras"<CSRNet-Keras@noreply.github.com>;
抄送: "1148640196"<1148640196@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [ZhengPeng7/CSRNet-Keras] 换成我自己的数据集生成数据集 (#2)




Closed #2.
