### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by eain3314** [ZhengPeng7/CSRNet_in_Keras#3]
请问一下，在csrnet那篇论文中，最后有psnr和ssim的比较，源网络不是有3次池化吗，那么最后怎么能比较psnr和ssim呢?

**Comment by ZhengPeng7** [comment]
You can see the description at the beginning of **chapter 3.1.2** in the original paper, where bilinear interpolation was used on the outputs to resize them to the shape of GT density maps.
![捕获](https://user-images.githubusercontent.com/25921713/62004724-548a4980-b15b-11e9-87b5-b26bab650dc6.PNG)
