### ISSUE TITLE
训练Loss为nan

### ISSUE THREAD

**Issue by 1286667673** [ZhengPeng7/CSRNet_in_Keras#5]
您好：
我想请教您些问题，自己实在看不出问题在哪了，我用‘Neerajj9’那个KERAS代码跑的时候，什么也没改，训练的loss不对啊，您知道是什么原因吗？
1/700 [..............................] - ETA: 2:54:46 - loss: 0.0024 - mean_squared_error: 4.1646e-05
(96, 128, 1)
  2/700 [..............................] - ETA: 2:36:14 - loss: nan - mean_squared_error: nan          
(96, 128, 1)
  3/700 [..............................] - ETA: 2:29:01 - loss: nan - mean_squared_error: nan
(96, 128, 1)
  4/700 [..............................] - ETA: 2:25:56 - loss: nan - mean_squared_error: nan
(96, 128, 1)
  5/700 [..............................] - ETA: 2:23:19 - loss: nan - mean_squared_error: nan

谢谢

**Comment by ZhengPeng7** [comment]
提供的信息比较有限. NaN的多半可能在数据处理时除以了0, 导致有某次回传的loss是NaN, 那之后的都是NaN了, 毕竟别的关于梯度之类的问题并不常见.
