### ISSUE TITLE
Problem in data generation 

### ISSUE THREAD

**Issue by sparafra** [ZhengPeng7/CSRNet_in_Keras#8]
`  File "/home/francesco/PycharmProjects/CSRNet-Keras/generate.py", line 46, in <module>
    DM = gen_density_map_gaussian(k, gt, sigma=sigma)`
`  File "/home/francesco/PycharmProjects/CSRNet-Keras/utils_gen.py", line 93, in gen_density_map_gaussian
    density_map[`
`ValueError: operands could not be broadcast together with shapes (47,898) (47,0) (47,898) `

How i can resolve it?

**Comment by zhongzhuC** [comment]
there are some problem about the “if np.sum(gaussian_map):”.The "if" only can limit next row instead of all the behind code

**Comment by ZhengPeng7** [comment]
No, there's no problem with the range of `if`.
That's an old problem😂 Actually, that's the problem of the SH-Tech dataset itself -- one version of that has _negative_ axes.
You can refer to the that issue in my SANet repository: [issue-1](https://github.com/ZhengPeng7/SANet-Keras/issues/2), [issue-2](https://github.com/ZhengPeng7/SANet-Keras/issues/6).
