### ISSUE TITLE
关于训练最佳权重的问题

### ISSUE THREAD

**Issue by ghost** [ZhengPeng7/CSRNet_in_Keras#9]
您好，我尝试过几次使用您的代码训练模型并且没有改变任何参数，但是每次训练结束后得到的最佳权重的MAE不一致且没有低于70过，请问这种情况正常吗，应该怎么改善呢？

**Comment by ZhengPeng7** [comment]
你好, 你可以看下你的augmentation那些选项有没有打开.

最佳权重不一样是正常的, 我没有设置固定随机数什么的(也没必要).

我的代码在SHA上的效果当时感觉不是很好, 最好也就readme里的67.x左右, 可以在SHB上跑下试试效果会很不错.

**Comment by Daniel2587** [comment]
> 你好, 你可以看下你的augmentation那些选项有没有打开.
> 
> 最佳权重不一样是正常的, 我没有设置固定随机数什么的(也没必要).
> 
> 我的代码在SHA上的效果当时感觉不是很好, 最好也就readme里的67.x左右, 可以在SHB上跑下试试效果会很不错

**Comment by ghost** [comment]
> 你好, 你可以看下你的augmentation那些选项有没有打开.
> 
> 最佳权重不一样是正常的, 我没有设置固定随机数什么的(也没必要).
> 
> 我的代码在SHA上的效果当时感觉不是很好, 最好也就readme里的67.x左右, 可以在SHB上跑下试试效果会很不错.

您好，请问您说的augmentation选项是指什么呢，怎样查看有没有开启？感谢您的解答。 @ZhengPeng7

**Comment by ZhengPeng7** [comment]
就是`utils_imgproc.py`里那些普通的图像增强... 如果是Crowd counting任务本身的话, 也可以改改生成density map的高斯核和窗口的参数.
此外, 我记得当时在训练到一个较低MAE后, 重新建个Adam, lr低100/1000倍来微调还可以有所提升(SHB能降~0.4)

但是说实话我的这个复现, 在SHA上的效果跑到70左右是正常的, readme里的68跑了很多遍才有的, 我当时精力有限不太清楚为什么SHA没有别人跑的好(虽然别的那几个非官方的代码我最初参考时基本没有能直接跑起来的, 都是shi, 更别说跑到readme的效果, 测试也测不起来).
